org: edsonguardamino
service: api-descuentosestudiantes

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:iam::051476014162:role/LabRole

functions:
  listar:
    handler: LeerDescuentos_Estudiante.lambda_handler
    events:
      - http:
          path: /descuentos/listar
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }
  modificar:
    handler: DescontarStockDescuento_Estudiante.lambda_handler
    events:
      - http:
          path: /descuentos/modificar
          method: put
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }

  eliminar:
    handler: DeleteDescuento_Estudiante.lambda_handler
    events:
      - http:
          path: /descuentos/eliminar
          method: delete
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }
  listargsi:
    handler: LeerDescuento_UniversidadGSI.lambda_handler
    events:
      - http:
          path: /descuentos/listar-gsi
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }
  validartoken:
    handler: ValidarTokenEstudiante.lambda_handler
    name: ValidarTokenEstudiante
